name= "pastebin-worker"
compatibility_date = "2023-11-28"
account_id= "9b631eb3d583d902cb764b4e5d0d52e8"
main = "src/index.ts"
workers_dev = false

vars = { ENVIRONMENT = "production" }
route = { pattern = "hllo-jiajia.us.kg", custom_domain = true }

kv_namespaces = [
  { binding = "PB", id = "c700dd8d97a648eb9aae64fa9a782e40" },
  { binding = "PBIMGS", id ="c16de1a687db4c88b4dfc6f43d732598" }
]

[site]
bucket = "./static/dist"
